### ISSUE TITLE
endpoint for providing information about application

### ISSUE THREAD

**Issue by edwardoboh** [zurichat/zc_plugin_company_files#182]
An endpoint for providing information about the application in json. Link to endpoint from homepage

**Comment by omzi** [comment]
**Slack Name**: omzi
**Live Link**: [http://companyfiles.zuri.chat/info](http://companyfiles.zuri.chat/info)

**Comment by markessien** [comment]
I dropped a comment earlier about the fields needed

**Comment by omzi** [comment]
**Slack Name**: omzi
**Link to PR**: [https://github.com/zurichat/zc_plugin_company_files/pull/205](https://github.com/zurichat/zc_plugin_company_files/pull/205)
**Live Link**: [http://companyfiles.zuri.chat/info](http://companyfiles.zuri.chat/info)

**Comment by markessien** [comment]
Nice one. Please remove the info about issues and the repo - not relevant

**Comment by omzi** [comment]
Ok Mark 😅. Thanks for the feedback.
