### ISSUE TITLE
ndpoint that provides a static list of the sidebar items

### ISSUE THREAD

**Issue by edwardoboh** [zurichat/zc_plugin_company_files#183]
An endpoint that provides a static list of the sidebar items that your application provides (Group Name and the particular items). It must not be dynamic yet. Endpoint should be in json

**Comment by Dipo-Jaiye** [comment]
Slack name: Dipo-Jaiye

Live link to test the issue resolution: http://companyfiles.zuri.chat/sidebar

**Comment by markessien** [comment]
Please view the comment I dropped on ericogia

**Comment by markessien** [comment]
Your icon urls have capitals and spaces. Please fix. Also, add something in the sidebar to indicate the badge. I.e how many notifications it shows - like All Files (5). Also, the badge type - Warning, Info.

**Comment by Dipo-Jaiye** [comment]
The urls have been made lower case and the spaces have been removed. Badges have been added for some sidebar items as well
Link to test: http://companyfiles.zuri.chat/sidebar

**Comment by markessien** [comment]
Nice
