### ISSUE TITLE
Collaborators Pane

### ISSUE THREAD

**Issue by berryboylb** [zurichat/zc_plugin_company_files#208]
Show the list of collaborators on the side under the total space component.

**Comment by markessien** [comment]
No review link

**Comment by billmal071** [comment]
The UI has been checked to see that it corresponds to the design.
the testing link when live is  [link](http://companyfiles.zuri.chat/activities) and in development is [dev](http://localhost:5500/activities)
Design - [design](https://www.figma.com/file/i4Fel38EJ0Jhrpz9PgLm2U/Team-Galileo--Company-File-Management?node-id=0%3A1)
