### ISSUE TITLE
Retrieve archived files (Backend)

### ISSUE THREAD

**Issue by i-Mhyke** [zurichat/zc_plugin_company_files#217]
A user should be able to view all their archived files.

**Comment by Alfred-Onuada** [comment]
I can handle this

**Comment by i-Mhyke** [comment]
This feature provides an endpoint where the user can view files that has been archived by an organization.
Pull request #256. 
The endpoint interacts with zuri core to retrieve the files stored in our plugin collection and provides a json data for the frontend to consume and display to the user.
The endpoint can be tested using this link: https://companyfiles.zuri.chat/api/v1/file/archive

Team **Gallileo**.
Slack Username: **Ihunaya**

**Comment by markessien** [comment]
Result page is completely blank

**Comment by i-Mhyke** [comment]
I've updated the link: https://companyfiles.zuri.chat/api/v1/files/archive
