### ISSUE TITLE
Basic Layout Setup and Tailwind Css

### ISSUE THREAD

**Issue by berryboylb** [zurichat/zc_plugin_company_files#222]
I've Set up the sidebar and set up Tailwindcss on the live site.
livelink
http://companyfiles.zuri.chat/

Pull Request: Sidebar
https://github.com/zurichat/zc_plugin_company_files/pull/195
Pull Request: Tailwindcss
https://github.com/zurichat/zc_plugin_company_files/pull/223

**Comment by markessien** [comment]
This is not needed at all. The sidebar is provided by zuri_main and not the plugin

**Comment by berryboylb** [comment]
So how do we route our pages, since the sidebar hasn't been provided yet? There are people working on files, trash etc.
