### ISSUE TITLE
route to save and retrieve data from zccore API endpoint.

### ISSUE THREAD

**Issue by devvyhac** [zurichat/zc_plugin_company_files#233]
An endpoint that reads and writes data from the ZC Core API endpoint at https://api.zuri.chat.

**`REQUEST TYPE`** : **`LIVE LINKS`** BELOW;

**`GET`** : _https://companyfiles.zuri.chat/read_  to read files data from the endpoint
**`POST`** : _https://companyfiles.zuri.chat/write_ to write files data to the endpoint

**`GET`** : _https://companyfiles.zuri.chat/folder/read_  to read files data from the endpoint
**`POST`** : _https://companyfiles.zuri.chat/folder/write_ to write files data to the endpoint

**`PR LINK:`** https://github.com/zurichat/zc_plugin_company_files/pull/236

**Comment by devvyhac** [comment]
I am working on it.

**Comment by markessien** [comment]
You have a reference to heroku here. Also, the endpoints don't work

**Comment by devvyhac** [comment]
> You have a reference to heroku here. Also, the endpoints don't work

It has been worked on now, please review @markessien
