### ISSUE TITLE
Adding files to a new folder

### ISSUE THREAD

**Issue by danieloladunjoye** [zurichat/zc_plugin_company_files#254]
- As a User, i want to add files to a new folder, view my folder description and also edit the description
- Figma File
   https://www.figma.com/file/KG0IhccGcavNxUagRofOsG/HNG-Portfolio?node-id=0%3A1

- Slack Username: Darniel

**Comment by just-osaze** [comment]
live link: https://companyfiles.zuri.chat/api/v1/files/addFileToFolder

track: BE

Slack userName: Osaze
