### ISSUE TITLE
Shared files

### ISSUE THREAD

**Issue by BJtone** [zurichat/zc_plugin_company_files#269]
- As a user I want to be to view my shared files so as to be able to keep track files I have shared.
- As a user I want to be able to give view/edit permission so as to be able to decide who can view/edit my files.
- https://www.figma.com/file/fdEbu0qDJETkcRqoV5ugJH/HNG?node-id=0%3A1
- Slack Username: BJtone

**Comment by paulynson** [comment]
Live Link: https://companyfiles.zuri.chat/shared
Slack username: codeFraction
Track: Frontend
